/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobile.app;

/**
 *
 * @author Steven
 */
public class Sign_Up extends javax.swing.JFrame {

    /**
     * Creates new form Sign_Up
     */
    public Sign_Up() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLabel1 = new javax.swing.JLabel();
        jTextFieldUsername1 = new javax.swing.JTextField();
        jTextFieldEmails = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabelPassword1 = new javax.swing.JLabel();
        jLabelPassword2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jRadioOptionButton1 = new javax.swing.JRadioButton();
        jRadioOptionButton2 = new javax.swing.JRadioButton();
        jRadioOptionButton3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/app.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextFieldUsername1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldUsername1.setText("Username");
        getContentPane().add(jTextFieldUsername1);
        jTextFieldUsername1.setBounds(200, 280, 360, 28);

        jTextFieldEmails.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldEmails.setText("Email");
        jTextFieldEmails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailsActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldEmails);
        jTextFieldEmails.setBounds(200, 340, 360, 28);

        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(200, 390, 360, 28);

        jPasswordField2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(200, 462, 360, 30);

        jLabelPassword1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelPassword1.setText("Password");
        getContentPane().add(jLabelPassword1);
        jLabelPassword1.setBounds(40, 390, 109, 20);

        jLabelPassword2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelPassword2.setText("Re-enter Password");
        getContentPane().add(jLabelPassword2);
        jLabelPassword2.setBounds(40, 470, 137, 22);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Sign Up");
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 750, 100, 31);

        jRadioOptionButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRadioOptionButton1.setText("Women Clothing, Shoes, handbags and accessories");
        getContentPane().add(jRadioOptionButton1);
        jRadioOptionButton1.setBounds(200, 530, 401, 31);

        jRadioOptionButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRadioOptionButton2.setText("Men Clothing, Shoes, handbags and accessories");
        getContentPane().add(jRadioOptionButton2);
        jRadioOptionButton2.setBounds(200, 600, 401, 31);

        jRadioOptionButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRadioOptionButton3.setText("Sign Up for emails about the latest looks, sales, events and more");
        getContentPane().add(jRadioOptionButton3);
        jRadioOptionButton3.setBounds(200, 660, 520, 31);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jLabel2, org.jdesktop.beansbinding.ELProperty.create("${}"), jLabel2, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 810, 850);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEmailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_Up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelPassword1;
    private javax.swing.JLabel jLabelPassword2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JRadioButton jRadioOptionButton1;
    private javax.swing.JRadioButton jRadioOptionButton2;
    private javax.swing.JRadioButton jRadioOptionButton3;
    private javax.swing.JTextField jTextFieldEmails;
    private javax.swing.JTextField jTextFieldUsername1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
